name: Upload Python Package

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  deploy-sdist:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Build and publish sdist
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m doit publish_sdist

  deploy-wheels:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
        pyversion: [3.5, 3.6, 3.7, 3.8]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Build and publish wheel
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m doit publish_wheel
